# Generated by Django 3.1.4 on 2020-12-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_hashtable_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='embedding',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='train',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.BinaryField(null=True),
        ),
    ]
