# Generated by Django 3.1.4 on 2020-12-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201210_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.DeleteModel(
            name='HashTable',
        ),
    ]
